Jinja2: 3.1.6
Markdown: '3.8'
MarkupSafe: 3.0.2
PyMuPDF: 1.26.0
PyYAML: 6.0.2
Pygments: 2.19.1
Werkzeug: 3.1.3
absl-py: 2.3.0
aiofiles: 24.1.0
annotated-types: 0.7.0
anyio: 4.9.0
astunparse: 1.6.3
cachetools: 5.5.2
certifi: 2025.4.26
charset-normalizer: 3.4.2
click: 8.2.1
contourpy: 1.3.2
cycler: 0.12.1
easyocr: 1.7.2
fastapi: 0.115.12
ffmpy: 0.6.0
filelock: 3.18.0
flatbuffers: 25.2.10
fonttools: 4.58.1
fsspec: 2025.5.1
gast: 0.6.0
google-auth: 2.40.2
google-genai: 1.18.0
google-pasta: 0.2.0
gradio: 5.32.1
gradio_client: 1.10.2
groovy: 0.1.2
grpcio: 1.72.1
h11: 0.16.0
h5py: 3.13.0
hf-xet: 1.1.2
httpcore: 1.0.9
httpx: 0.28.1
huggingface-hub: 0.32.3
idna: '3.10'
imageio: 2.37.0
keras: 3.10.0
kiwisolver: 1.4.8
lazy_loader: '0.4'
libclang: 18.1.1
markdown-it-py: 3.0.0
matplotlib: 3.10.3
mdurl: 0.1.2
ml_dtypes: 0.5.1
mpmath: 1.3.0
namex: 0.1.0
networkx: '3.5'
ninja: 1.11.1.4
numpy: 2.1.3
opencv-python: 4.11.0.86
opencv-python-headless: 4.11.0.86
opt_einsum: 3.4.0
optree: 0.16.0
orjson: 3.10.18
packaging: '25.0'
pandas: 2.2.3
pillow: 11.2.1
protobuf: 5.29.5
psutil: 7.0.0
py-cpuinfo: 9.0.0
pyasn1: 0.6.1
pyasn1_modules: 0.4.2
pyclipper: 1.3.0.post6
pydantic: 2.11.5
pydantic_core: 2.33.2
pydub: 0.25.1
pyparsing: 3.2.3
pypdf: 5.6.0
python-bidi: 0.6.6
python-dateutil: 2.9.0.post0
python-multipart: 0.0.20
pytz: '2025.2'
requests: 2.32.3
rich: 14.0.0
rsa: 4.9.1
ruff: 0.11.12
safehttpx: 0.1.6
scikit-image: 0.25.2
scipy: 1.15.3
semantic-version: 2.10.0
setuptools: 80.9.0
shapely: 2.1.1
shellingham: 1.5.4
six: 1.17.0
sniffio: 1.3.1
starlette: 0.46.2
sympy: 1.14.0
tensorboard: 2.19.0
tensorboard-data-server: 0.7.2
tensorflow: 2.19.0
termcolor: 3.1.0
tifffile: 2025.6.1
tomlkit: 0.13.2
torch: 2.7.0
torchvision: 0.22.0
tqdm: 4.67.1
typer: 0.16.0
typing-inspection: 0.4.1
typing_extensions: 4.14.0
tzdata: '2025.2'
ultralytics: 8.3.147
ultralytics-thop: 2.0.14
urllib3: 2.4.0
uvicorn: 0.34.3
websockets: 15.0.1
wheel: 0.45.1
wrapt: 1.17.2

